### ISSUE TITLE
Battery monitor to general linux robots stack

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#1]
- https://kforge.ros.org/turtlebot/trac/ticket/76

We suggest a new "linux_robots" stack or whatnot. Put things like this there.

**Comment by rgariepy** [comment]
linux_robots seems like a "common"/"utils" stack name - at risk of clutter

**Comment by LucidOne** [comment]
On Wed, 2012-09-26 at 05:33 -0700, rgariepy wrote:

> linux_robots seems like a "common"/"utils" stack name - at risk of
> clutter
> 
> —
> Reply to this email directly or view it on GitHub. 

linux_drivers seems appropriate only for drivers that won't work on
other platforms like FreeBSD, OSX, etc. Specifically drivers that make
calls to the kernel / ACPI.

**Comment by stonier** [comment]
I was just about to start moving tickets from [trac](https://kforge.ros.org/turtlebot/trac)...not actually working on most of them yet, but thanks for the input guys.

**Comment by stonier** [comment]
Just put it into its own turtlebot_netbook package for now 2dc134ccb5a3833435ee8cf4528567fd29fb7d5a.
