### ISSUE TITLE
Changelog subsections incapacitate catkin_tag_changelog

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#100]
Jorge, I think you started putting in a human effort for subsections like:

```
2.2.x - hydro, bugfixing
========================
```

which becomes after a `catkin_generate_changelog`:

```
2.2.x - hydro, bugfixing
========================

Forthcoming
-----------
* remove cmake install rule for now obsoleted upstart files.
```

I like it, but catkin_tag_changelog can now no longer find the forthcoming labels and update. We need to either:
- Remove the top most subsection label in each changelog OR
- See if giving the subsection a different label (maybe the 2.2.x is confusing catkin_tag_changelog) works
- Improve catkin_tag_changelog to ignore this kind of subsection label

**Comment by stonier** [comment]
Seems to be very sensitive. I tried many variations
- 2.2.x - hydro, bugfixing -> Release 2.2.x - hydro, bugfixing
- Changing underlining from === -> ---- -> ^^^^^ -> 2x-----
  - Sometimes works, but fails again if you update the second section header below too.

Just took the top section heading out of this stack for the 2.2.1 release (see #99).

**Comment by bit-pirate** [comment]
That´s a leftover from the old times. Just remove those sections.

2013/9/14 Daniel Stonier notifications@github.com

> Seems to be very sensitive. I tried many variations
> - 2.2.x - hydro, bugfixing -> Release 2.2.x - hydro, bugfixing
> - Changing underlining from === -> ---- -> ^^^^^ -> 2x-----
>   - Sometimes works, but fails again if you update the second section
>     header below too.
> 
> Just took the top section heading out of this stack for the 2.2.1 release
> (see #99 https://github.com/turtlebot/turtlebot/pull/99).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/100#issuecomment-24434802
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by corot** [comment]
yes, I noticed this long time ago, so I have being removing this extra header whenever it bothers catkin_tag_changelog, instead of removing all systematically.

Sorry, I didn't tell cause I thought it's a tinny detail.

**Comment by corot** [comment]
I noticed this long time ago, but instead of removing all systematically, I only did whenever it bothers me in a new release. Now is gone in all our repos.

Sorry, I didn't notice everyone as it's a trivial issue.
