### ISSUE TITLE
depthimage_to_laserscan starves if depth_registration is true

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#103]
On 3dsensor.launch, depthimage_to_laserscan looks for depth/image_raw topic, but if we are using depth_registration (the default behavior) it will not work because in this case depth image topic is depth_registered/image_raw.

We should make remapping conditional.

**Comment by bit-pirate** [comment]
+1

Or just set the default to `depth_registered/image_raw`.

**Comment by tfoote** [comment]
It also could be setup with a mux nodelet.

**Comment by robinJKU** [comment]
I think this is a more complicated issue: https://github.com/ros-drivers/openni_launch/issues/7
If depht registration is turned on, I can't see any depth images nor a point cloud. According to the above link it seems like a bug in the openni driver.

**Comment by jihoonl** [comment]
https://github.com/turtlebot/turtlebot/commit/3e32933c829e308600707a9f971334d13d1cbe19 should have resolved this issue.
