### ISSUE TITLE
not finding platform_info

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#106]
sometimes when I pressed back button from app to return to remocon

it couldn't find platform_info service and shutdown

**Comment by stonier** [comment]
please move to android_remocons

**Comment by bit-pirate** [comment]
Maybe make one issue here at turtlebot summarising the various issues you
encountered and link to them (e.g. hydro ISO issues). Will make it easier
to track them down.

2013/10/25 Daniel Stonier notifications@github.com

**Comment by stonier** [comment]
Cannot reproduce.
