### ISSUE TITLE
improve error introspection with android

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#108]
At the moment, it is really hard to whether there is software failure in robot with android. 
Even reading terminal, it is hard to know whether app is properly terminated or app manager get crashed.

**Comment by stonier** [comment]
Are you saying the app manager is crashing on stop apps?

**Comment by stonier** [comment]
Please move to android_remocons

**Comment by jihoonl** [comment]
https://github.com/rosjava/android_remocons/issues/36
