### ISSUE TITLE
Kinect depth mode: 2 -> 8

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#11]
On recommendation from someone here, mode of 2 was really slow.

Change it and test it for a while.

**Comment by stonier** [comment]
- Mode 2 is VGA (640x480)
- Mode 8 is QVGA (320x240)

**Comment by stonier** [comment]
Dont know if you'd call this an enhancement!

**Comment by tfoote** [comment]
I don't think this is perferrable.  I'd make sure that you're subscribing with the right datatype such that you're doing pointer passing not serializing and deserializing.  You need to be careful how you subscribe to the point cloud messages such that they publish and subscribe with boost shared pointers of _exactly_ the same type pcl::PointCloud<PointXYZ> or pcl::PointCloud<PointXYZRGB> depending on if registered or not.

**Comment by stonier** [comment]
Thanks for the info Tully.
