### ISSUE TITLE
Error with diagnostics.yaml for roomba

### ISSUE THREAD

**Issue by hofes** [turtlebot/turtlebot#110]
If the robot base is set to roomba I get an error when launching minimal.launch. It seems that the redirection in param/roomba/diagnostics.yaml to param/create/diagnostics.yaml is not working. 
A work around that worked for me was to hardcode the create base for the diagnostics node in launch/includes/robot.launch.xml.

**Comment by tfoote** [comment]
Please provide a way to reproduce your problem with both the expected output and the observed output.  It looks like the parameter is being passed correctly in minimal.launch https://github.com/turtlebot/turtlebot/blob/hydro-devel/turtlebot_bringup/launch/minimal.launch#L11

**Comment by mayrjohannes** [comment]
just set the environmental variable TURTLEBOT_BASE to roomba, then the error occurs.
The launch file is doing everything right, but I think the script in param/roomba/diagnositcs.yaml is not working.

By the way, there is also an spelling error in the second line of the launch file. rhoomba shoud be roomba.

**Comment by stonier** [comment]
Spelling fix in 97a72c6bff2687169caaf818fd34628e6b8cb7af

**Comment by lukacu** [comment]
I can also confirm this problem. The only fix that works is to copy the full `diagnostics.yaml` file from `create` to `roomba` folder. Should I create a pull request for this?

**Comment by bit-pirate** [comment]
> Should I create a pull request for this?

Yes, please! :+1:
