### ISSUE TITLE
Remove app manager specific data in robot.launch.xml

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#115]
I don't think this data belongs into `robot.launch.xml` (https://github.com/turtlebot/turtlebot/blob/hydro-devel/turtlebot_bringup/launch/includes/robot.launch.xml ):

```
  <!-- important generally, but specifically utilised by the current app manager -->
  <param name="robot/name" value="$(optenv ROBOT turtlebot)"/>
  <param name="robot/type" value="turtlebot"/>
```

I guess those are leftovers, since similar data is specified in the `minimal_with_app_manager.launch` launcher (https://github.com/turtlebot/turtlebot/blob/hydro-devel/turtlebot_bringup/launch/minimal_with_appmanager.launch ) as well:

```
  <!-- App manager -->
  <arg name="robot_name" default="$(optenv ROBOT_NAME turtlebot)"/>
  <arg name="robot_type" default="$(optenv ROBOT_TYPE turtlebot)"/>
```

@stonier @jihoonl @corot any idea?

**Comment by stonier** [comment]
These parameters need to be set somewhere. The app manager definitely uses them. And I _think_ nobody else does, but they're interesting parameters to have around even when there is no app manager.

Shouldn't be hardcoded to turtlebot nor ROBOT there though. Should be using the args filtered down from minimal.launch and co, or similar.

**Comment by jihoonl** [comment]
These variables are configured via env hook.

https://github.com/turtlebot/turtlebot/commit/1d8989d9521c94a1afefeda4ce3f9d1934f45818
