### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#119]
Guys, if you don't claim branches, I'm going to clean them at the end of the week (Dec 1). I've attached the last author to have committed to these branches below. Check the item below if you want to keep it.
- [ ] 3dsensor_test @
- [ ] common @zklapow 
- [x] capabilities_integration @bit-pirate 
- [ ] master @corot
- [ ] new_appmanager @corot
- [ ] turtlebot-x @corot
- [ ] updates @jihoonl

**Comment by bit-pirate** [comment]
> capabilities_integration @bit-pirate

Don't take what is mine! :-P

**Comment by jihoonl** [comment]
updates and new_appmanager have been deleted.

I think turtlebot-x is a legacy from waiterbot integration

**Comment by jihoonl** [comment]
master should be the last rosmake code used in groovy

**Comment by bit-pirate** [comment]
> master should be the last rosmake code used in groovy

If this is true, renaming it to fuerte/rosmake/rosbuild or similar might be a good idea.

**Comment by jihoonl** [comment]
@stonier  whats going on with this.

**Comment by stonier** [comment]
- master deleted, it's a trivial commit away from groovy.
- 3dsensor_test deleted, it was merged back into the main branch
- turtlebot-x deleted, it was an almost trivial xacro commit with experimental laser on top.
- common deleted, it was a parallel dashboard experiment that is really old now.
- capabilities_integration deleted, it is merged into hydro-devel.
