### ISSUE TITLE
Some topics created by 3dsensor.launch produce no messages

### ISSUE THREAD

**Issue by spragunr** [turtlebot/turtlebot#123]
Under Groovy, 3dsensor.launch created a large number of topics, any of which could be visualized in rviz.  Under Hydro, more or less the same topics are created, but only a subset of topics ever produce any messages.  For example the /scan topic is silent.   The mix of working topics changes based on depth registration.  For example /scan works if the file is launched like this,

`3dsensor.launch depth_registration:=false`

but then some other topics stop publishing.

I'm not sure if this is the intended behavior, but it will certainly be confusing for the intended Turtlebot audience. 

Here is a ROS Answers thread where the issue is discussed:

http://answers.ros.org/question/112391/nothing-published-to-scan-under-hydro/

**Comment by stonier** [comment]
Thanks for posting...I'll check this when I have a chance.
