### ISSUE TITLE
indigo-devel branching

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#126]
While working on waiterbot, I figure out that the turtlebot hydro-devel branch is not compatible with rocon hydro-devel branch. In order to keep the waiterbot code working with up-to-date rocon, we need to upgrade turtlebot to be compatible with up-to-date rocon hydro-devel as well. 

Shall we create indigo-devel and keep it compatible with rocon?

**Comment by stonier** [comment]
Why not just upgrade turtlebot hydro devel. Im definitely not in favour of
maintaining two branches if we dont need to.

**Comment by jihoonl** [comment]
If hydro-devel is to prepare indigo, sure.

**Comment by stonier** [comment]
The rocon hydro-devel branches are the same. I only happen to have an indigo branch since I don't have hydro on my machine.
