### ISSUE TITLE
update minimal_with_appmanager.launch

### ISSUE THREAD

**Issue by dwlee** [turtlebot/turtlebot#134]
Due to the changes in rocon_app_manager, it also needs to be updated.

**Comment by bit-pirate** [comment]
Updates are already in the _caps_rapps_upgrade_ branch: https://github.com/turtlebot/turtlebot/blob/caps_rapps_upgrade/turtlebot_bringup/launch/rapp_platform.launch

**Comment by jihoonl** [comment]
robot_name, and rapp package whitelist used to be configurable with optenv, environment variable. It would be good to keep it as it was.

https://github.com/turtlebot/turtlebot/blob/hydro/turtlebot_bringup/launch/minimal_with_appmanager.launch#L1-L18

**Comment by jihoonl** [comment]
minimal_with_app_manager has been removed in indigo. Closing the issue.
