### ISSUE TITLE
Failed to install ros-hydro-turtlebot with unmet dependencies

### ISSUE THREAD

**Issue by b2220333** [turtlebot/turtlebot#135]
When I run:

sam@sam:~/code/ros_hydro_overlay/src$ sudo apt-get install ros-hydro-turtlebot ros-hydro-turtlebot-apps ros-hydro-turtlebot-viz ros-hydro-turtlebot-simulator ros-hydro-kobuki-ftdi
Reading package lists... Done
Building dependency tree  
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libbullet-dev : Depends: libbullet (= 2.80-0) but it is not going to be installed
 ros-hydro-kobuki-ftdi : Depends: ros-hydro-ecl-command-line but it is not going to be installed
 ros-hydro-turtlebot : Depends: ros-hydro-linux-hardware but it is not going to be installed
                       Depends: ros-hydro-turtlebot-bringup but it is not going to be installed
                       Depends: ros-hydro-turtlebot-description but it is not going to be installed
 ros-hydro-turtlebot-apps : Depends: ros-hydro-pano-core but it is not going to be installed
                            Depends: ros-hydro-pano-py but it is not going to be installed
                            Depends: ros-hydro-pano-ros but it is not going to be installed
                            Depends: ros-hydro-turtlebot-actions but it is not going to be installed
                            Depends: ros-hydro-turtlebot-calibration but it is not going to be installed
                            Depends: ros-hydro-turtlebot-core-apps but it is not going to be installed
                            Depends: ros-hydro-turtlebot-follower but it is not going to be installed
                            Depends: ros-hydro-turtlebot-navigation but it is not going to be installed
                            Depends: ros-hydro-turtlebot-panorama but it is not going to be installed
                            Depends: ros-hydro-turtlebot-teleop but it is not going to be installed
 ros-hydro-turtlebot-simulator : Depends: ros-hydro-turtlebot-gazebo but it is not going to be installed
 ros-hydro-turtlebot-viz : Depends: ros-hydro-turtlebot-dashboard but it is not going to be installed
                           Depends: ros-hydro-turtlebot-interactive-markers but it is not going to be installed
                           Depends: ros-hydro-turtlebot-rviz-launchers but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
sam@sam:~/code/ros_hydro_overlay/src$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libbullet
The following NEW packages will be installed:
  libbullet
0 upgraded, 1 newly installed, 0 to remove and 78 not upgraded.
6 not fully installed or removed.
Need to get 0 B/963 kB of archives.
After this operation, 2456 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
(Reading database ... 795377 files and directories currently installed.)
Unpacking libbullet (from .../libbullet_2.80-0_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/libbullet_2.80-0_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libHACD.so.2.80', which is also in package libbullet2.80 2.80.2-ubuntu1~precise1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libbullet_2.80-0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
sam@sam:~/code/ros_hydro_overlay/src$ 

Although this problem seems not so related to turtlebot, but I have to solve it before going on.
How to solve it?

Thank you~

**Comment by tfoote** [comment]
You have a preexisting conflict with the bullet package you need to fix that before you will be able to install almost anything.  Did you manually install bullet previously?

This isn't a problem with TurtleBot. Please take a look at more generic forums about apt support and if you can't find the solution ask for help on answers.ros.org.
