### ISSUE TITLE
Allow providing a custom robot description to turtlebot_bringup/minimal.launch

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#136]
That is, instead of always providing base, stacks and 3d_sensor arguments, give also the alternative of providing a path to a custom urdf file. The idea is to avoid forcing people with a customized Turtlebot to replicate the chain

> minimal.launch -> robot.launch.xml -> description.launch.xml

just to load their own URDF robot description.

I mark this as question because I seek for some consensus before doing nothing. I can understand that some people can consider this misguided (though handy): why should turtlebot_bringup/description.launch.xml load a description different from those officially accepted as Turtlebot descriptions?

**Comment by bit-pirate** [comment]
+1

PR 주세요! :-)

**Comment by corot** [comment]
응, 응,   +2 있으면 해요!

**Comment by corot** [comment]
I didn't know, but in fact, it used to be like this on turtlebot 1:

https://github.com/turtlebot/turtlebot/blob/5a90ab0f53305551277528fb96a0456a321d237b/turtlebot_bringup/minimal.launch

**Comment by corot** [comment]
Well.... maybe it's not that good idea at the end:
- We must tweak many launch files, increasing the number of arguments by 2 (urdf_file + custom_robot flag)
- It's much simpler just to overwrite the robot_description in your own custom robot launchers
