### ISSUE TITLE
Indigo turtlebot.rosinstall still gets hydro-devel branches

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#149]
So this error appears: https://github.com/turtlebot/turtlebot_apps/issues/88

Are we ready to clone indigo branches?

**Comment by stonier** [comment]
It's using rosinstallers in `yujin_tools`. See the [wiki page](http://wiki.ros.org/turtlebot/Tutorials/indigo/Installation). No real reason except that I wasn't planning on announcing that some updates were going on at the time, so didn't reflect that in the real rosinstall.
