### ISSUE TITLE
Merge kobuki apps

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#15]
Most are the same, we have a different chirp. 

Not going to worry about doing anything different for turtlebot2 till we have a better gateway model/android pairing setup a few months down the line (us, austin and osrf).

**Comment by stonier** [comment]
Moved this to the turtlebot apps stack, turtlebot/turtlebot_apps/issues/3.

Only need to remember to update the turtlebot_bringup/apps platform specific app lists here.

**Comment by stonier** [comment]
Goal is to have one turtlebot_bringup/apps/turtlebot_apps.installed file (currently create and kobuki versions).

Mostly this entails:
- editing launchers in turtlebot_teleop/sounds/follower so that they work. 
- compare with launchers in kobuki_android_apps and kobuki_other_apps

One major exception is chirps....which compiles and runs an entirely kobuki based program. Turtlebot1 doesn't actually use create's sounds, just moos (I think).

I think change turtlebot_bringup/launch/components -> turtlebot_bringup/launch/includes is a good idea to do now as well (same approach as openni).

**Comment by jihoonl** [comment]
android_teleop.launch requires mjpeg_server package to stream video. Should we put this dependency in the rosinstall file?

**Comment by stonier** [comment]
Not really - we're not going to be updating mjpeg_server code. For anything we're not likely to update I use debs, for anything we are likely to update (or doesn't have debs), I put in the rosinstall file.

**Comment by jihoonl** [comment]
Done. and tested. All five apps(Teleop, Make a map, Nav, Chipr, and Follower) are launched without error.
