### ISSUE TITLE
openni_launch -> openni2_launch

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#156]
Anything holding us back from possibly doing this for indigo?

**Comment by mikeferguson** [comment]
Are you still using Kinects? openni2 doesn't support the Kinect, the recommendation has been to use freenect instead.

**Comment by stonier** [comment]
Yeah, just learned the old kinect wouldn't run on openni2. We might have to switch soon though and we're already using Asux Xtions on our other robots. Have to stay with openni for now as long as turtles are selling with kinects.
