### ISSUE TITLE
System configuration

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#16]
What's the best way to kill this? At the moment we have at least three things we'd like to configure.
- /proc/xxx naming for the battery.
- The base - create or kobuki
- The stacks - t1 or t2.

The current plan is to set environment variables:
- TURTLEBOT_BASE - you can see in minimal.launch
- TURTLEBOT_STACKS - not yet
- TURTLEBOT_BATTERY - not yet

and pull them into roslaunched args:

```
<arg name="base" value="$(optenv TURTLEBOT_BASE kobuki)"/> 
```

More preferable ideas?

**Comment by LucidOne** [comment]
Our plan was to use turtlebot_config to handle this and the usb serial
port issues. Vendors would ship a vendor config debian that describes
the laptop, base, stacks, etc and the turtlebot_config would read that
config file and generate the appropriate /etc/ros files.
turtlebot_config already has a gui that can walk users through base and
stack selection.

The URDF compositor can then output the right urdf to /etc/ros/urdf
based on the base + acessories. ie. kinect vs Xtion, cupholder, arm,
buttons, etc.

All of this can happen in the USB installer automagically if the debs
have the right deps setup.

**Comment by stonier** [comment]
That looks like an option - I'll leave in the environment variables for now so I can continue, and come back to finding a way to integrating this once we're a bit more complete.

**Comment by stonier** [comment]
Bill, got some questions about this - I'll put them on turtlebot-config.

**Comment by stonier** [comment]
Look at urdf compositer with bill when he arrives.

**Comment by stonier** [comment]
Going with the environment variables for now, I'll write up some notes on the wiki.

These work fine - even including adding extensions. The only thing we need is something that can stitch together urdf's on the fly and cache them somewhere given the environment variables currently present.
