### ISSUE TITLE
turtelbot_bringup env hook missing dependency on turtlebot_navigation in Indigo

### ISSUE THREAD

**Issue by trainman419** [turtlebot/turtlebot#163]
I have a very minimal turtlebot setup, without navigation, and every time I start a terminal I get an error message stating that turtlebot_navigation cannot be found. Since turtlebot_navigation is not a dependency for turtlebot_bringup, I don't have it installed.

Poking around a bit, it looks like this is caused by one of the new environment hooks in Indigo: https://github.com/turtlebot/turtlebot/blob/cfcee011e8dcdce67740545ac8b27407df30eb1d/turtlebot_bringup/env-hooks/25.turtlebot.sh.em#L20

I'm not familiar enough with the turtlebot to know the best way to fix this, but I have a few suggestions:
- suppress the error message in the environment hook
- move the affected variable to an environment hook in the turtlebot_navigation package
- add a dependency on turtlebot_navigation

**Comment by stonier** [comment]
Good catch austin.

> move the affected variable to an environment hook in the turtlebot_navigation package

I like this option. @jihoonl can you hit this one on the head for us and give it some road miles on the waiterbots?

**Comment by stonier** [comment]
Shifted to turtlebot_apps in https://github.com/turtlebot/turtlebot_apps/commit/3ea2c306120774e8ed7e69e4e3fce3eca9f5426e
