### ISSUE TITLE
Kobuki minimal.launch without robot_pose_ekf

### ISSUE THREAD

**Issue by pedropgusmao** [turtlebot/turtlebot#165]
Hello,
I have a clearpath turtlebot 2 which came with groovy and launched robot_pose_ekf from kobuki/_minimal.launch 
Unfortunately after moving the code to a new laptop, I have seen that the kobuki/minimal.launch from ros-hydro does not come with the launch node robot_pose_ekf. 

I know that I can manually insert such node, but I would like to know if it wouldn't be better to have it already in the turtlebot_bringup/launch/include/kobuki/minimal.launch

Thanks,

Pedro

**Comment by stonier** [comment]
It makes sense if your wheel odometry and gyro are coming from different sources OR you possibly have another source of odometry.

The kobuki driver already fuses these internally however, so no point adding another layer to the onion unless necessary. Of course, if you want to add another odometry input (e.g. visual odometry), it would then make sense to have something like this combining the kobuki odometry with the new source of odometry.
