### ISSUE TITLE
include kobuki.minimal install

### ISSUE THREAD

**Issue by pedropgusmao** [turtlebot/turtlebot#166]
Hello there,

shouldn't  kobuki/minimal.install just include the https://github.com/yujinrobot/kobuki/blob/indigo/kobuki_node/launch/minimal.launch ?

Thanks, 
Pedro

**Comment by stonier** [comment]
Yeah, it probably could, but at the end of the day we have always had a few minor variations between kobuki's setup and turtlebot's setup. Note that they both use the same `kobuki_node/param/base.yaml` as default settings and that is probably sufficient for mollifying the streamliners who want to eliminate all redundancies :neckbeard:.
