### ISSUE TITLE
Another installation problem

### ISSUE THREAD

**Issue by mkdmkk** [turtlebot/turtlebot#169]
In the installation tutorial, there are three key steps; installing recon, kabuki, and turtlebot.
The first two steps were done. But, I failed to do the third step.

> wstool init src -j5 https://raw.github.com/yujinrobot/yujin_tools/master/rosinstalls/indigo/turtlebot.rosinstall
> update complete.
> source ~/kobuki/devel/setup.bash
> rosdep install --from-paths src -i -y
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> turtlebot_stdr: Cannot locate rosdep definition for [stdr]
> turtlebot_dashboard: Cannot locate rosdep definition for [create_dashboard]
> turtlebot_gazebo: Cannot locate rosdep definition for [create_gazebo_plugins]

**Comment by jihoonl** [comment]
`turtlebot_stdr` dependency has been resolved with referenced issue.

And please ignore create gazebo dependencies. `create gazebo plugin` isn't working now and it should not be an issue if you are using real robot.

**Comment by stonier** [comment]
Should disable these from `package.xml` files and add `CATKIN_IGNORE` instead of having this loose end which is continually raised.

**Comment by jihoonl** [comment]
It is disabled in turtlebot_simulator, and catkin_ignore is added in create_gazebo_plugins.

**Comment by bit-pirate** [comment]
> And please ignore create gazebo dependencies. create gazebo plugin isn't working now and it should not be an issue if you are using real robot.
> 
> Should disable these from package.xml files and add CATKIN_IGNORE instead of having this loose end which is continually raised.

But then please make an issue for each disabled dependencies. Otherwise we probably will overlook some, when we do the full release and end up with broken dependencies.

**Comment by bit-pirate** [comment]
E.g. here: https://github.com/turtlebot/turtlebot_simulator/commit/ac530c1ad2ee735b80683378ebcf8e8028263b8e#commitcomment-8474551

**Comment by mkdmkk** [comment]
I have tried to re-install the ROCON.
When I entered the command, wstool init -j5 src https://raw.githubusercontent.com/robotics-in-concert/rocon_demos/turtlebot_concert/concert.rosinstall, the following errors popped up:

Exception caught during install: Error processing 'turtlebot_apps' : [turtlebot_apps] Checkout of https://github.com/turtlebot/turtlebot_apps.git version sim_param into /home/mkk/rocon/src/turtlebot_apps failed.
Error processing 'rocon_app_platform' : [rocon_app_platform] Checkout of https://github.com/robotics-in-concert/rocon_app_platform.git version sim_param into /home/mkk/rocon/src/rocon_app_platform failed.
Error processing 'rocon_tutorials' : [rocon_tutorials] Checkout of https://github.com/robotics-in-concert/rocon_tutorials.git version gazebo_concert into /home/mkk/rocon/src/rocon_tutorials failed.
Error processing 'concert_services' : [concert_services] Checkout of https://github.com/robotics-in-concert/concert_services.git version sim_param into /home/mkk/rocon/src/concert_services failed.

ERROR in config: Error processing 'turtlebot_apps' : [turtlebot_apps] Checkout of https://github.com/turtlebot/turtlebot_apps.git version sim_param into /home/mkk/rocon/src/turtlebot_apps failed.
Error processing 'rocon_app_platform' : [rocon_app_platform] Checkout of https://github.com/robotics-in-concert/rocon_app_platform.git version sim_param into /home/mkk/rocon/src/rocon_app_platform failed.
Error processing 'rocon_tutorials' : [rocon_tutorials] Checkout of https://github.com/robotics-in-concert/rocon_tutorials.git version gazebo_concert into /home/mkk/rocon/src/rocon_tutorials failed.
Error processing 'concert_services' : [concert_services] Checkout of https://github.com/robotics-in-concert/concert_services.git version sim_param into /home/mkk/rocon/src/concert_services failed.

**Comment by jihoonl** [comment]
`sim_param` branch and gazebo_concert branch has been merged into upstream `indigo`. 

The following commits should have resolved.

https://github.com/robotics-in-concert/rocon_demos/commit/58e3b4184ad4ff59dd4a98ce81b7be77a5f190a6
https://github.com/robotics-in-concert/rocon_demos/commit/9bc62809762f029230ed148ae8ff97d1ce3e2903

**Comment by stonier** [comment]
@mkdmkk  Why are you using the `rocon_demos` rosinstaller? That one is the unofficial one we use internally and not officially supported continuously.

The rosinstaller we always maintain is at https://raw.github.com/robotics-in-concert/rocon/indigo/rocon.rosinstall. i.e. the same one on the [turtlebot wiki installation instructions](http://wiki.ros.org/turtlebot/Tutorials/indigo/Installation).
