### ISSUE TITLE
Provide mass and inertia real values for 3D camera, stacks and poles

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#172]
Now, the TB looks too much "light" in Gazebo.

I have no idea how to estimate the inertia, really. That's why I mark this also as a question.

Incidentally, I also noticed that the "virtual" links (optical axes, etc.) have an <inertial> tag with dummy low values. I think we can safely remove these tags and keep just one for the whole camera.

**Comment by stonier** [comment]
Poles should be given by the matrix for **Solid cylinder of radius r, height h and mass m** provided [here](http://en.wikipedia.org/wiki/List_of_moments_of_inertia).

You could also roughly model the stacks using the same equation and camera by a solid cuboid.

If you get time, give that a shot and see how it looks.

**Comment by stonier** [comment]
Note, the exact xacro variables are extracted from those matrices from the upper triangle only (it's symmetrical):

```
[ ixx ixy ixz ]
[ ixy iyy iyz ]
[ ixz iyz izz ]
```

**Comment by stonier** [comment]
Pull request in.
