### ISSUE TITLE
rename ROBOT_NAME and ROBOT_TYPE

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#177]
Use TURTLEBOT as it's prefix.
- ROBOT_NAME -> TURTLEBOT_NAME
- ROBOT_TYPE -> TURTLEBOT_TYPE

**Comment by mikeferguson** [comment]
Are you sure you really want to do this? ROBOT, ROBOT_NAME, and ROBOT_TYPE are used on other robots -- for instance on PR2. I also thought long-term it was intended that these variables might be usable for things like capabilities or concert configuration (and thus, leaving them ROBOT-agnostic, makes them useful)

**Comment by stonier** [comment]
I'm fine either way. I can understand the logic of having robot/capabilities/concert generic variables, but I can also see that as a _new_ user, having them all as `TURTLEBOT_xxx` does make it very easy to discover what environment variables are set/configurable. @jihoonl, what is your opinion?

**Comment by jihoonl** [comment]
I think both @mikeferguson and @stonier have valid points. 

I lean to @mikeferguson opinion though. I think the better place for these variables are near `rocon_app_manager` because `ROBOT_NAME`, `ROBOT_TYPE`, `CAPABILITIES`, `INTERACTIONS`, and `RAPPS` are rapp manager configurations which can be independent from hardware related configurations. 

I also agree that TURTLEBOT prefix makes turtlebot configuration discovery easier as novice user.

So to satisfy both points..how about migrate configuration env-hooks into [rocon_app_manager](https://github.com/robotics-in-concert/rocon_app_platform/tree/indigo/rocon_app_manager) and create a script which shows the current env configurations for the turtlebot?

for example, 

```
> turtlebot_configuration
= CURRENT TURTLEBOT ENVs =
ROBOT_NAME=turtlebot
ROBOT_TYPE=turtlebot
CAPABILITES=false
CAP_LIST=[]
INTERACTIONS=false
TURTLEBOT_BASE=kobuki
TURTLEBOT_STACKS=hexagons

...
```

**Comment by tfoote** [comment]
That looks like a good compromise.

ROCON things stay generic and TurtleBot specific ones prefixed with
TURTLEBOT

**Comment by jihoonl** [comment]
Here is a proposal to create env-hook in `rocon_app_manager`. Please leave your opinion. I plan to make it happen today or tomorrow. https://github.com/robotics-in-concert/rocon_app_platform/issues/267

**Comment by stonier** [comment]
I have made an dictatorial decision to have them all as simply `TURTLEBOT_XXX` for now. :neckbeard: That means they can be pre-loaded by env-hooks (easy for users to find) and they don't conflict with anybody else. 

Main reason though is this was the shortest path to making sure we get an indigo release out very soon without having to deal with funny bugs here and there (95% of variables had already been converted to this style over the last year already).

Can think about this more properly in the future if we ever need to.
