### ISSUE TITLE
update rosinstall files

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#183]
to use turtlebot_interactions instead of turtlebot_viz.

**Comment by jihoonl** [comment]
@bit-pirate do we still need [turtlebot_capabilities.rosinstall](https://github.com/turtlebot/turtlebot/blob/indigo/turtlebot_capabilities.rosinstall)?

**Comment by jihoonl** [comment]
@bit-pirate  bump.

**Comment by stonier** [comment]
Turtlebot rosinstalls have long since been cleaned out. Closing.
