### ISSUE TITLE
rocon_interactions dependency for minimal.launch

### ISSUE THREAD

**Issue by spragunr** [turtlebot/turtlebot#187]
minimal.launch currenlty fails unless ros-indigo-rocon-interactions has been installed manually.

**Comment by jihoonl** [comment]
ah it was missing dependency in [rocon_app_manager](https://github.com/robotics-in-concert/rocon_app_platform/tree/indigo/rocon_app_manager)

It has been fixed by https://github.com/robotics-in-concert/rocon_app_platform/commit/4bb5907063852e7fbf98279be866765ce9fc6d3c
