### ISSUE TITLE
Push turtlebot1 stack meshes down into own folder

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#19]
such as turtlebot2 stack meshes are now in ../meshes/turtlebot2_stack.
Any objections?

**Comment by LucidOne** [comment]
I feel like there should be a turtlebot2_description package and/or a kobukibot_description package

**Comment by bit-pirate** [comment]
Kobukibot is Turtlebot2 consisting of Kobuki + Turtlebot2 stack . We officially discarded the first name to avoid confusion (also see [naming issue](https://github.com/yujinrobot/kobuki/issues/150) in the kobuki repo). We are working on moving turtlebot2-specific files to the turtlebot repo and keeping kobuki-only things in the kobuki repo. Hence, you will find the kobuki description there and the turtlebot2 description in the turtlebot repo.

**Comment by stonier** [comment]
Hit this again - I missed some of the details when marcus raised the naming issue. See there for details.
