### ISSUE TITLE
Documentation migration guide for hydro->indigo

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#191]
Add stuff here which is different to hydro and document this:
- [x] 3d sensor 
- [x] qt interactions (rocon_remocon)
- [x] android interactions
- ~~World Canvas~~
- ~~Concert client version bringup~~

**Comment by jihoonl** [comment]
World canvas?

**Comment by jihoonl** [comment]
- Concert client version bringup will be followed up by #204.
- World Canvas documentation will be followed up by https://github.com/corot/world_canvas/issues/47
