### ISSUE TITLE
exported libary doesn't exist

### ISSUE THREAD

**Issue by dirk-thomas** [turtlebot/turtlebot#192]
Where is the library `turtlebot_teleop` supposed to come from (https://github.com/turtlebot/turtlebot/blob/fee9733124358c011ed6bd0a711e73da1500d64c/turtlebot_teleop/CMakeLists.txt#L11)?

I would guess it needs to be removed from the catkin_package() call.

**Comment by jihoonl** [comment]
Removed from catkin_package call.
