### ISSUE TITLE
linux_hardware: will support continue on Indigo and Jade?

### ISSUE THREAD

**Issue by jack-oquin** [turtlebot/turtlebot#193]
This package looks useful, but I see no release yet for Indigo.

Is continuing support intended? 

Or, is it deprecated? If so, what alternatives would you recommend?

**Comment by jihoonl** [comment]
It has been renamed and migrated to https://github.com/ros-drivers/linux_peripheral_interfaces

**Comment by jihoonl** [comment]
Ref: https://github.com/ros-drivers/linux_peripheral_interfaces/issues/1

**Comment by jack-oquin** [comment]
OK, thanks for explaining it. I'll use linux_peripheral_interfaces, instead.
