### ISSUE TITLE
Remaining turtleobt tutorial works

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#197]
![img_1670](https://cloud.githubusercontent.com/assets/1556736/6660871/cfb9faa2-cbe5-11e4-9c89-c212bdf2ea9f.JPG)

**Comment by jihoonl** [comment]
- [x] Fix chirp meow -> moo
- [x] fix `no preffered rapp` warning
- [x] interacting with the robot tutorial
- [x] customising the turtle tutorial
- [x] create rapp tutorial
- [x] create interaction tutorial
- [x] overhaul bringup tutorials
- [x] flag a multi robot tutorial
- [x] stage/gazebo tutorial link
- [x] check 3d visualization for depth image/registration - explain `either` works. 
- [x] amcl tutorial, use `TURTELBOT_MAP_FILE` env. variable instead of roslaunch arg
- [x]  put mapping tutorials under indigo subfolders and customiese them (qt?)
- [x] return to main page links should go to &distro=indigo
- [x] Drop STDR
- [x] Migration Guide

**Comment by stonier** [comment]
Return to links should be:

```
[[Robots/TurtleBot|TurtleBot main page|&distro=indigo]]
```

not

```
[[Robots/TurtleBot|TurtleBot main page]]
```

**Comment by stonier** [comment]
@jihoonl can you update with current status?

**Comment by jihoonl** [comment]
Done jobs are checked.

**Comment by jihoonl** [comment]
Flag a multi robot tutorial? What is this?

**Comment by stonier** [comment]
Empty page, with a TODO and listed on the main tutorials page, and we come back after the rocon documentation (like the android tutorial).

**Comment by jihoonl** [comment]
Done.
