### ISSUE TITLE
Verfiy and unify kinect&xtion urdfs

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#20]
Check to what extend we can unify the kinect & xtion related urdfs for both turtlebot 1 & 2.

If the camera mounting in both robots is different we could create a common kinect/xtion.urdf, which is include by turtlebot_kinect.urdf and turtlebot2_kinect.urdf (same for xtion). The robot-specific would include the mounting plate and poles.

In this process varify the calibration parameters for both cameras and in combination with both robots.
I remember we found some error in those parameters.

**Comment by LucidOne** [comment]
Please look at our URDF compositor, it already handles some of this and works with the new plates for "turtlebot_metric"
https://github.com/IHeartRobotics/iheart-ros-pkg/tree/master/ihe_hardware/urdf_compose

**Comment by bit-pirate** [comment]
OK, I will. I only took a brief look at it so far.

**Comment by stonier** [comment]
Ours is working, let's look at the compositor when bill arrives.
