### ISSUE TITLE
Later Release Task

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#203]
This is follow-up issue of #170 to tackle Later Release Tasks.
- [ ] Turtlebot teleop code switch to [ros-teleop](https://github.com/ros-teleop) implementations(https://github.com/turtlebot/turtlebot/issues/180)
- [ ] Capabilities on Turtlebot
- [x] Drop in world canvas in place of the map_store ready for android app support.
- [x] Android apps (once rosjava on indigo is supported and world canvas is in)

**Comment by stonier** [comment]
Closing this - we're now well into kinetic. Teleop issue recreated in #227. Capabilities I'll drop for now since there's not an engineer dedicated for this (would be great to advertise them though).
