### ISSUE TITLE
Outdated comment "Currently Broken" in follower application

### ISSUE THREAD

**Issue by nampi** [turtlebot/turtlebot#214]
The comment “(Currently Broken)” looks outdated in this line https://github.com/turtlebot/turtlebot/blame/indigo/turtlebot_bringup/interactions/pairing.interactions#L81. I have tried to launch it, it works correctly in gazebo concert (simulation). Could you check the reason of this comment, please?

**Comment by stonier** [comment]
Fixed in 6f99772e63ee66b3fd4288350d1f79b2e7e65c45. Cherry picked to kinetic.
