### ISSUE TITLE
cannot find turtlebot.urdf.xacro file.

### ISSUE THREAD

**Issue by asimay** [turtlebot/turtlebot#216]
in file: turtlebot/turtlebot_description/test.launch
I cannot find the following files:
*_arg name="urdf_file" default="$(find xacro)/xacro.py '$(find turtlebot_description)/robots/turtlebot.urdf.xacro'" *_
please tell me where is turtlebot.urdf.xacro file. thanks

**Comment by tfoote** [comment]
That test looks to be out of date. There are more specific filenames in this directory: https://github.com/turtlebot/turtlebot/tree/indigo/turtlebot_description/robots

**Comment by corot** [comment]
Fixed with 2723773486625ca647ff6d7326206a459987dd3c. I chose kobuki + hexagons + kinect as the canonical TB2... :thinking: I don't want to hurt feelings!
