### ISSUE TITLE
Rename kinect.launch -> 3dsensor.launch

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#22]
We're hoping to start using the asus more exclusively. This renaming makes sense.

**Comment by jihoonl** [comment]
We should recheck android_map_nav.launch later

it references kinect_depth_frame in line 16.

**Comment by jihoonl** [comment]
I'm omitting turtlebot_arm stack. It has too many unknown things.

**Comment by jihoonl** [comment]
turtlebot_gazebo stack uses kinects many places.  I am not sure how I should fix this. omitting this as well.

**Comment by jihoonl** [comment]
Apps are tested and working well.

**Comment by jihoonl** [comment]
I will keep it open to discuss for arm and gazebo stack
