### ISSUE TITLE
Rocon node keeps dying when roslaunch minimal.launch

### ISSUE THREAD

**Issue by jasonswee** [turtlebot/turtlebot#233]
![error](https://cloud.githubusercontent.com/assets/13789695/18282402/980b6d04-7493-11e6-8efe-33a7d761dd45.png)

Rocon nodes keeps dying and it fails to connect to turtlebot

**Comment by stonier** [comment]
Are you on indigo or kinetic?

**Comment by jasonswee** [comment]
@stonier  indigo 

I wonder if the issue is due to missing package ros-indigo-rqt-wrapper
I created a [rocon issue](https://github.com/robotics-in-concert/rocon/issues/39)

**Comment by tfoote** [comment]
Closing this as it does not appear to be a turtlebot issue. My guess is that you have not run message generation appropriately in your workspace(s). I suggest that you open a question on http://answers.ros.org with a full description of how you setup your workspace following our guidelines at http://wiki.ros.org/Support

**Comment by stonier** [comment]
Has the wrong source branch for turtlebot I expect.
