### ISSUE TITLE
Bumping behavior

### ISSUE THREAD

**Issue by jonpol01** [turtlebot/turtlebot#246]
Hi.. is it possible to customized the turtlebot bumping behavior?
ex. if it bumps let it do something.

If yes, can you please tell where to begin.?

**Comment by bit-pirate** [comment]
This kind of usage question is better asked on [ROS Answers](http://answers.ros.org/). We are trying to keep this issue tracker focusing on code-related issues and feature requests.

For the TurtleBot 2 (using the Kobuki base) you could subscribe to the [bumper events topic](https://github.com/yujinrobot/kobuki_msgs/blob/kinetic/msg/BumperEvent.msg) and then build logic around that. Refer to the [kobuki random walker](http://wiki.ros.org/kobuki_random_walker) as reference.
