### ISSUE TITLE
Groovy updates

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#25]
List of updates to make things groovy-ready.

**Comment by stonier** [comment]
No more pcl dependency. It is now a 3rd party library and cmake now needs to use find_package to find it. See updates in kobuki_node and pointcloud_to_laserscan.

It gets installed via ros-groovy-pcl, but is not a ros package.

**Comment by stonier** [comment]
rqt has no debs, so installing it via sources.

*****************\* BROKEN PACKAGE - QT_GUI_CPP *******************

Also, rqt cpp stuff is not compiling (we're using python, so not a big issue).

**Comment by jihoonl** [comment]
*****************\* BROKEN PACKAGE - ROBOT_STATE_PUBLISHER *******************

In order to make the command work below...create robot_state_publisher directory in /opt/ros/groovy/lib and copy /opt/ros/groovy/bin/robot_state_publisher to the directory

rosrun robot_state_publisher robot_state_publisher
- https://kforge.ros.org/robotmodel/Trac/ticket/8 - fixed

**Comment by stonier** [comment]
Is that the right way to handle binaries that are 'catkin' installed in /bin? 

Yes - binaries should go in lib/pkg_name, refer to http://www.ros.org/reps/rep-0122.html#lib-ros-package-name

**Comment by jihoonl** [comment]
*****************\* BROKEN PACKAGE - MAP_STORE *******************

Get it from source

> hg clone  https://kforge.ros.org/mapstore/hg map_store

It's also in the turtlebot_groovy.rosinstall since there is no deb yet.

Changes in map_store CMakeLists.txt
1. uncomment 
   rosbuild_add_boost_directories()
2. add rosbuild_link_boost under each executable

rosbuild_link_boost(map_saver thread)
rosbuild_link_boost(map_manager thread)

Unfortunately no tracker for this - is there even a maintainer?
- https://kforge.ros.org/projects/mapstore/

**Comment by corot** [comment]
*****************\* BROKEN PACKAGE - MJPEG_SERVER *******************

I removed the dependency on opencv. Appart from that, it compiles

Also no tracker/maintainer, probably have to ping bosch.
- http://ros.org/wiki/mjpeg_server#

**Comment by corot** [comment]
*****************\* BROKEN PACKAGE - ROSBRIDGE_SUITE *******************

Get it from source

> https://github.com/RobotWebTools/rosbridge_suite.git

It's also in the turtlebot_groovy.rosinstall since there is no deb yet.

Changes in rosbridge_suite/tf_smart_throttle/CMakeLists.txt
1. Add line 
   rosbuild_link_boost(${PROJECT_NAME} thread)

Pull request:
- https://github.com/RobotWebTools/rosbridge_suite/pull/2 - fixed

**Comment by stonier** [comment]
*****************\* BROKEN PACKAGES - IMAGE_PIPELINE *******************

Seems that the image pipeline failed to install alot of nodelet plugins (lots of bleeding when running 3dsensor.launch)
- https://github.com/ros-perception/image_pipeline/blob/master/depth_image_proc/nodelet_plugins.xml
- https://github.com/ros-perception/image_pipeline/blob/master/image_proc/nodelet_plugins.xml
- https://github.com/ros-perception/image_pipeline/blob/master/image_view/nodelet_plugins.xml
- https://github.com/ros-perception/image_pipeline/blob/master/stereo_image_proc/nodelet_plugins.xml
- https://github.com/ros-perception/image_common/blob/master/image_transport/default_plugins.xml
- https://github.com/ros/nodelet_core/blob/master/nodelet_topic_tools/test/test_nodelets.xml

Copying them into /opt/ros/groovy/package-name for now stopped alot of gore.

The image pipleine/common stacks are all fixed (Oct 31), just weren't in deb yet. The last one for test nodelets...
- https://github.com/ros/nodelet_core/issues/1

openni_camera is also failing to find image transport plugins - ros-groovy-image-transport-plugins made it happy, maybe this is supposed to be a dep of openni_camera?

**Comment by stonier** [comment]
Can't show images in rviz - image plugin can't load a required image_transport plugin. Same with image_view. Following workaround fixes it....but I'm not sure if it is the right solution (breaks in a buildspace instead of installspace?)

In groovy/share/image_transport/default_plugins.xml, on the first line, prefix the path with: '../../'. Same in image_view/nodelet_plugins.xml.
- https://github.com/ros-perception/image_pipeline/issues/1
- https://github.com/ros-perception/image_common/issues/4

**Comment by stonier** [comment]
3dsensor.launch - we no longer have the deprecated openni_camera/OpenNINodelet any longer. Trying with openni_camera/driver instead.

**Comment by stonier** [comment]
Status at Seoul: 8am
- most everything is compiling with the hacks above
- turtlebot_bringup/minimal.launch works for kobuki (create might be fine as well, but haven't tested)
- turtlebot_bringup/3dsensor.launch: we switched to openni_camera/driver nodelet
  - not sure if this is the right thing to do, since it doesn't produce point clouds
  - there is an rgb image, but it's shoddy and black and white
  - depth/registered image is there too
- gazebo from source compiles, runs with blue cloudy skies, but no more than that.
- rviz is a sensitive beast

**Comment by corot** [comment]
CMakeList.txt / manifest.xml to make turtlebot apps compile

turtlebot_actions
1. Remove dependency on opencv2 and add two missing dependencies e440c3fbd18f81cc2bc8200559b927a692fbb2c0  5e305e3fe4034c422184efcf3448cfe59507f451
2. Link against boost libraries  b3914435ce356c7e909da6e60290319311f0f725

turtlebot_follower
1. Link against pcl libraries  2cb4177f6a21daab96801522908ce50b57f64640

pano
1. Remove dependency on opencv2  5bf278723bc216a74addf6fc171ab1d90ef7ebe9
2. Link against opencv2 libraries  fdac5d8aefc01f5a0b23ec48d88c633b78401e4d

**Comment by jihoonl** [comment]
Openni Migration guide from deprecated to stable api.
We may have to follow this.. 

http://ros.org/wiki/openni_camera_deprecated

**Comment by stonier** [comment]
Reading that, we probably need to make use of [depth_image_proc](http://ros.org/wiki/depth_image_proc) which provides various nodelets for 2D/3D processing. Maybe just look in openni_launch to see how they use it.

I still thing openni_camera/driver is the way to go - it's minimal. We tack on the required depth processing on top.

**Comment by stonier** [comment]
Only 3dsensor fixes needed. Continuing in #32
