### ISSUE TITLE
[Kinetic] odometry issue on the turtlebot2

### ISSUE THREAD

**Issue by tzhivkov** [turtlebot/turtlebot#264]
Hi All,

I'm relatively new to the ROS community (but not to the ROS platform). I recently downloaded the latest drivers (sorry I can't tell which exactly as it was many in one go) that really messed up the odometry for the physical kobuki base used for the Turtlebot2. 
I performed some tests after I noticed the odom issue.
I used 4 different Turtlebot2s and 2 different laptops, with an asus xtion pro camera. The result was the same in each case. I start up bringup minimum launch , amcl demo launch and start rviz, I observed a drift to the right even though the robot  was driving in a completely straight line. Also occasionally this drift suddenly makes the amcl predicted arrows expand in all directions and the turtlebot2 starts warping about the map (in rviz still). I changed to the only laptop which had Ubuntu 14.04 and indigo installed and ran bringup minimum, amcl demo and rviz. Performing the same test on 2 of the turtlebot2s and the results were perfect as they always are. 

Could anyone advise me on what to do, is this a known issue or a new issue?

Thanks!
Tiz

**Comment by tfoote** [comment]
I'm not familiar with any recent updates that would change the behavior of odometry.

For questions we generally ask that you please ask http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments. Please reask your question there. And link back here for others reference.

When you reask over there it would be really helpful if you had some screenshots or screencasts of the behavior of what you're doing. As well as copy and pasting any console outputs to look for warnings or errors.

Also what map are you using for your amcl demo? Does your environment look similar to the map? Also have you tried running the vehicle around without localization but with odometry to verify if it's actually an issue with odometry or with localization?
