### ISSUE TITLE
only target Groovy.. 

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot#27]
I don't think that we should try to support fuerte with all the changes that have been made. 
- rqt is not supported in fuerte... i.e. the dashboard is not backwards compatible and we should not support 2 versions
- this will make many of the launch files much simpler
- etc

End result of the discussion:
- Don't break existing fuerte debs - that's a major api change in the middle of a release which is not best practice.
- Target groovy, work hard at solving 3d sensor and gazebo issues.
- Provide minimal support for a turtlebot2 fuerte rosinstall - bringup, rviz, android apps.

**Comment by LucidOne** [comment]
On 11/12/2012 03:20 AM, Melonee Wise wrote:

> I don't think that we should try to support fuerte with all the 
> changes that have been made.
> - rqt is not supported in fuerte... i.e. the dashboard is not
>   backwards compatible and we should not support 2 versions
> - this will make many of the launch files much simpler
> - etc
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/turtlebot/turtlebot/issues/27.

If possible, I would like to support Fuerte for the initial release and 
drop support immediately after.
This would provide a smoother transition for developers who have not yet 
switched to Groovy.

**Comment by mmwise** [comment]
what is the main reason for trying to support fuerte on turtlebot 2? the current turtlebot stacks work on fuerte... this seems like a lot of extra complexity in the launch files for little gain. 

rxtools is not going to be released in groovy and rqt will not be released in fuerte so you have a dead lock on the dashbaord.

**Comment by mmwise** [comment]
i miss spoke.. dirk informs me that rqt is not support on lucid but is released in fuerte and might not work completely.. and rxtools is deprecated in groovy.

**Comment by stonier** [comment]
I'm actually all for groovy just to eliminate extra effort. 

And also so the daunting prospect can light the fire beneath our bums!

**Comment by stonier** [comment]
Also, on rqt - I've been using it in fuerte to build a kobuki rqt test suite. But I agree - I was talking to Ze'ev about the dashboard. Far easier to do that in groovy otherwise we'd need to double up alot of effort to make a dashboard work in fuerte. The robot dashboard rqt infrastructure is not in fuerte.

**Comment by rgariepy** [comment]
On Mon, Nov 12, 2012 at 4:18 AM, IHeartRobotics notifications@github.comwrote:

> On 11/12/2012 04:02 AM, Melonee Wise wrote:
> 
> > what is the main reason for trying to support fuerte on turtlebot 2?
> > the current turtlebot stacks work on fuerte... this seems like a lot
> > of extra complexity in the launch files for little gain.
> > 
> > rxtools is not going to be released in groovy and rqt will not be
> > released in fuerte so you have a dead lock on the dashbaord.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/turtlebot/turtlebot/issues/27#issuecomment-10280585
> > .
> > 
> > I'm not sure the people buying TurtleBot 2s are quite ready mentally to
> > upgrade to Groovy. I'd like to support Fuerte momentarily to smooth the
> > transition.

+1

**Comment by stonier** [comment]
It is easy for me to wish for support a move directly to groovy, so I should probably remove myself from voting on this. Exactly what is required to support both?
- robot_state_publisher has a funny name change from fuerte - groovy
- openni nodelet now must upgrade from the depracated openNINodelet
- if we move to supporting the new dashboard, then dashboard will be broken in fuerte
- possibly, really different gazebo support (?)
- ...

And Bill, Ryan, do you guys have much time to invest to help keep support for fuerte? Time is the one thing we don't have in abundance.

Also, do you want deb support to override T1 deb support or source install support for fuerte?

**Comment by tfoote** [comment]
robot_state_publisher will be at least providing
backwards compatibility for that, if not completely reverting that change.
https://code.ros.org/trac/ros-pkg/ticket/5576

I think that supporting groovy only for the new turtlebot is a good idea
from the maintenance point of view as well.

On Mon, Nov 12, 2012 at 5:54 AM, Daniel Stonier notifications@github.comwrote:

> It is easy for me to wish for support a move directly to groovy, so I
> should probably remove myself from voting on this. Exactly what is required
> to support both?
> - robot_state_publisher has a funny name change from fuerte - groovy
> - openni nodelet now must upgrade from the depracated openNINodelet
> - if we move to supporting the new dashboard, then dashboard will be
>   broken in fuerte
> 
> And Bill, Ryan, do you guys have much time to invest to help keep support
> for fuerte? Time is the one thing we don't have in abundance.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/27#issuecomment-10287951.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by jihoonl** [comment]
Can we just say partially support and provide packages that are currently available? 
Turtlebot_bringup and turtlebot_description should work in fuerte.

**Comment by stonier** [comment]
I'll make a concrete proposal here:
- Don't break existing fuerte debs - that's a major api change in the middle of a release which is not best practice.
- Target groovy, work hard at solving 3d sensor and gazebo issues.
- Provide minimal support for a turtlebot2 fuerte rosinstall - bringup, rviz, android apps.

**Comment by rgariepy** [comment]
After discussing further, it's our team's collective opinion that a
Groovy-only TBT build is acceptable from a support perspective.

-Ryan

**Comment by stonier** [comment]
Update the original post with our target.
