### ISSUE TITLE
IMU has huge covariance

### ISSUE THREAD

**Issue by ulassbin** [turtlebot/turtlebot#271]
I am currently trying to improve navigation with fusing some sensors. The IMU data obtained from turtlesim has huge covariances in 'orientation' and 'angular_velocity'. Is there a way to fix these covariances to make it more realistic? The image below is one of the imu data readings while the robot is standing still.

![image](https://user-images.githubusercontent.com/38883137/47252644-bf7e5580-d450-11e8-9722-4f0389957684.png)

**Comment by tfoote** [comment]
What simulation are you running? turtlesim it not a turtlebot simulator. Which turtlebot model are you simulating? What values would you would suggest are more realistic?

**Comment by tfoote** [comment]
This looks to be a duplicate of https://github.com/turtlebot/turtlebot_simulator/issues/69
