### ISSUE TITLE
remove dependancy on rosbridge

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot#28]
we should create a turtlebot_web or move this stuff to turtlebot_apps... turtlebot should have the absolute minimal deps... in fact we want to move pointcloud_to_laserscan someplace eventually..

https://github.com/turtlebot/turtlebot/blob/master/turtlebot_bringup/launch/roboworld.launch

**Comment by stonier** [comment]
Agreed while the web stuff is an 'optional'.
