### ISSUE TITLE
robot algorithms stack

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#29]
Mel brought this up in #28 when talking about moving pointcloud_to_laserscan.

I'd like a generic robot_algorithms (or similar) stack where we can dump simple err 'robot algorithms'. Point cloud to laser scan, random wandering mode, motion patterns, gyro heading calibration/drift estimation etc. 

I've got a few that we're making for kobuki (manufacturing programs) that would be perfectly usable by turtlebot and other bases, but I can't put in places like kobuki or turtlebot without wierd or circular dependencies.

Thinking for just 1s more on the topic, 'robot_algorithms' is far too generic. We're talking about simple algorithms for mobile bases here.

**Comment by tfoote** [comment]
That definitely seems too broad.  I'd suggest breaking them into groups
related to their application.  And as we're moving foward toward groovy
there's no longer a grouping requirement then can just stand on their own.

On Mon, Nov 12, 2012 at 4:06 AM, Daniel Stonier notifications@github.comwrote:

> Mel brought this up in #28https://github.com/turtlebot/turtlebot/issues/28when talking about moving pointcloud_to_laserscan.
> 
> I'd like a generic robot_algorithms (or similar) stack where we can dump
> simple err 'robot algorithms'. Point cloud to laser scan, random wandering
> mode, motion patterns, gyro heading calibration/drift estimation etc.
> 
> I've got a few that we're making for kobuki (manufacturing programs) that
> would be perfectly usable by turtlebot and other bases, but I can't put in
> places like kobuki or turtlebot without wierd or circular dependencies.
> 
> Thinking for just 1s more on the topic, 'robot_algorithms' is far too
> generic. We're talking about simple algorithms for mobile bases here.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/29.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by stonier** [comment]
Leaving everything in turtlebot_apps for now, just reorganising into software/turtlebot software/app manager apps.

Later when we drop in a new app manager (need to talk design at some point, both ourselves and osrf are getting close to the point on really working on this) we can reorganise better.
