### ISSUE TITLE
Debian release checklist

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#30]
Stacks are listed in some sort of relative order.
- [Build Status Updates](http://www.ros.org/debbuild/groovy.html)

**Done**
- Wet (Catkin)
  - zeroconf_msgs [0.2.1] - [ChangeList](http://ros.org/wiki/zeroconf_msgs/ChangeList)
  - zeroconf_avahi_suite [0.2.2]  - [ChangeList](http://ros.org/wiki/zeroconf_avahi_suite/ChangeList)
  - ecl_tools [0.50.2] - [ChangeList](http://ros.org/wiki/ecl_tools/ChangeList)
  - ecl_lite [0.50.5] - [ChangeList](http://ros.org/wiki/ecl_lite/ChangeList)
  - ecl_core [0.50.5] - [ChangeList](http://ros.org/wiki/ecl_core/ChangeList)
  - ecl_navigation [0.50.3] - [ChangeList](http://ros.org/wiki/ecl_navigation/ChangeList)
  - kobuki_msgs [0.3.1] - [ChangeList](http://ros.org/wiki/kobuki_msgs/ChangeList)
  - yujin_ocs
    - Groovy [0.2.3] - [ChangeList](http://ros.org/wiki/yujin_ocs/ChangeList)
    - Hydro [0.3.0] - [ChangeList](http://ros.org/wiki/yujin_ocs/ChangeList)
  - kobuki [0.3.9-2] - [ChangeList](http://ros.org/wiki/kobuki/ChangeList)
  - yujin_maps
    - Groovy [0.1.0]
    - Hydro [0.1.0]
- Dry
  - kobuki_desktop [0.1.6] - [ChangeList](http://ros.org/wiki/kobuki_desktop/ChangeList)
  - kobuki_description [0.3.2] - only temporary stack while xacro is not catkinized.
  - turtlebot_create [2.0.1] - [ChangeList](http://ros.org/wiki/turtlebot_create/ChangeList)
  - turtlebot_create_desktop [2.0.0] - [ChangeList](http://ros.org/wiki/turtlebot_create_desktop/ChangeList)
  - turtlebot [2.0.2] - [ChangeList](http://ros.org/wiki/turtlebot/ChangeList)
  - turtlebot_apps [2.0.2] - [ChangeList](http://ros.org/wiki/turtlebot_apps/ChangeList)
  - turtlebot_viz [2.0.1] - [ChangeList](http://ros.org/wiki/turtlebot_viz/ChangeList)
  - turtlebot_simulator [1.9.1] - [ChangeList](http://ros.org/wiki/turtlebot_simulator/ChangeList)

**Todo**
- turtlebot_arm

**Comment by stonier** [comment]
zeroconf debs available, kobuki pending.

**Comment by stonier** [comment]
Bit perplexed why shadow doesn't update with successful jenkins jobs (some are waiting 2-3 days already) - that's making things slow. But we're getting there.

**Comment by tfoote** [comment]
Are you looking at shadow?  It's only for electric now.  The new repo
updated by the debbuild jobs is "building" at
http://50.28.27.175/repos/building/

And that should sync to shadow-fixed each time a full sweep finishes. (It's
done inside the metapackage jobs for each arch, you can see the last time
it should have run by checking their execution time)

On Sun, Nov 18, 2012 at 3:36 PM, Daniel Stonier notifications@github.comwrote:

> Bit perplexed why shadow doesn't update with successful jenkins jobs (some
> are waiting 2-3 days already) - that's making things slow. But we're
> getting there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/30#issuecomment-10497144.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by stonier** [comment]
I was looking at shadow-fixed and not finding some debs that were tagged as having built 5 days go. 

Having said that...suddenly everything updated! Not sure whether 1) I'm losing the plot or 2) I hadn't reloaded when I thought I had or 3) something else. Anyway, I'll keep an eye on things and update if I have the problem again.

**Comment by stonier** [comment]
Kobuki deb is finally compiling. Can now move on to the turtlebot debs.

Do new dry releases upload modified tarballs only when there is a version bump?  I'll check next time I try - I think this was the kobuki deb delay problem.

**Comment by bit-pirate** [comment]
Status update:
Can't get turtlebot to build, because it is missing ros-groovy-zeroconf-avahi-suite, which I couldn't get rolled so far. Currently jenkins is stuck right at the start and aborts after a while, because apt-get update can't find destinations like packages.ros.org ...

**Comment by tfoote** [comment]
Yeah, our DNS server went offline, and the failover is up, but we need to
wait for all the DNS caches to timeout and find the new upstream DNS
servers.

On Fri, Nov 30, 2012 at 5:38 PM, Marcus Liebhardt
notifications@github.comwrote:

> Status update:
> Can't get turtlebot to build, because it is missing
> ros-groovy-zeroconf-avahi-suite, which I couldn't get rolled so far.
> Currently jenkins is stuck right at the start and aborts after a while,
> because apt-get update can't find destinations like packages.ros.org ...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/30#issuecomment-10911314.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by stonier** [comment]
The wrestling continues - groovy! Some updates
- Started bumping turtlebot_xxx releases to 1.9.0 (seems more proper). 
- Added ChangeLists links above so changes can be followed by whoever needs to.
- Stack turtlebot dependencies are fixed, and its prereleasing, release pending.
  - Turtlebot stack concept is bringup, only putting in there the minimal dependencies, others moving to turtlebot_apps.

Only exception to the minimal dependencies is 3dsensor. I did think about moving that to apps as well, but 1) cant think of any apps that would not want to run the 3d sensor in a minimal way (openni_camera/driverNodelet and lazy depthimage_to_scan), and 2) it is part of turtlebot. Ideally then, it should be in minimal.launch too, but it's still too unstable.

**Comment by stonier** [comment]
Bumps for kobuki_msgs 0.1.6 and kobuki 0.1.9 (catkin fixes and autodocking).

Turtlebot stack 1.9.0 now rolling. Updated the [turtlebot](http://ros.org/wiki/turtlebot) wiki page (tutorials not in sync though).

**Comment by stonier** [comment]
turtlebot_apps, kobuki_desktop, turtlebot_simulator pending releases. mjpeg_server is something we'll have to wait for bosch to rerelease for groovy.

**Comment by stonier** [comment]
kobuki_msgs, kobuki now 0.2.x (diverging from fuerte).

**Comment by stonier** [comment]
- rqt just changed, kobuki_desktop and turtlebot_simulator pending an update.
- ecl_lite, ecl_core bumped to 0.50.3 to bugfix quantal and built.
- turtlebot_apps failing on a problem in depthimage_to_laserscan - https://github.com/ros-perception/depthimage_to_laserscan/issues/2

**Comment by stonier** [comment]
Dependency for mjpeg_server removed (https://github.com/turtlebot/turtlebot_apps/commit/73829323b193ca2f6669ab97a226e2c8d06a9822). Android app for teleop doesn't actually need it in android_teleop.launch. Originally, it was part of a rough web app setup introduced in https://github.com/turtlebot/turtlebot_apps/commit/06007ced68d6353682e8140400c97c217d4617e7, but that mechanism is no longer working and it is also calling a pr2_teleop in turtlebot_teleop.html as well.

Instead, let's look at a proper web app infrastructure going towards hydra.

**Comment by corot** [comment]
- kobuki_msgs nothing to do
- kobuki_desktop last release was 0.1.2, not 0.1.0; ChangeLog added
- kobuki released as 0.2.2
- turtlebot_create released as 1.9.2
- turtlebot_viz released as 1.9.2
- turtlebot released as 1.9.2
- turtlebot_apps released as 1.9.1
- turtlebot_simulator released as 1.9.1

**Comment by corot** [comment]
- yujin_ocs 0.1.3 released

**Comment by corot** [comment]
- kobuki released as 0.2.3
- turtlebot released as 1.9.4

all others have no significatif changes

**Comment by corot** [comment]
- kobuki released as 0.2.4
- turtlebot_apps released as 1.9.2

**Comment by bit-pirate** [comment]
A quick comment about catkinising:
As it has been discussed in the TurtleBot meeting at Willow last week, catkinisation of all Turtlebot-related packages is targeted for Hydro.

**Comment by corot** [comment]
- turtlebot_viz released as 1..9.3

**Comment by corot** [comment]
- turtlebot_create_desktop first release as 1.9.0 (to keep turtlebot_whatever version system)

**Comment by corot** [comment]
- kobuki_desktop released as 0.1.3 (with changes required by turtlebot_create_desktop)

**Comment by stonier** [comment]
Xacro stack - it's blocking catkinization of any of turtlebot. 

Is this likely to be catkinized soon, or ever?

**Comment by mikeferguson** [comment]
xacro is needed by PR2, and I know they intend to catkinize all PR2 stuff by Hydro.

**Comment by stonier** [comment]
If you catch a sniff of it before we do, let us know here. It'd be nice to switch all the development over to catkin as soon as possible. This half-catkin, half-not is a bit tedious.

**Comment by stonier** [comment]
kobuki_description 0.3.0 added for dry releasing.

Can't avoid that split - we need a kobuki catkin for windows driver builds.

**Comment by mikeferguson** [comment]
Will do -- I notice xacro is currently listed as maintained by Stu, which means it is on the list of things currently being reallocated to new maintainers, I'll see if I can find out what the timeline on that reallocation is.

**Comment by chadrockey** [comment]
Last I heard, the plan is for core and pr2 packages to be catkin for
hydro.  There is a good chance that after I turtle, all released debian
packages must be catkin.

Xacro is now maintained by William:
https://github.com/ros/xacro/tree/catkinize

**Comment by stonier** [comment]
Great, thanks guys.

**Comment by stonier** [comment]
New kobuki_msgs, kobuki, yujin_ocs catkin stacks are away!

Turtlebot 2.0 rollovers coming...

**Comment by stonier** [comment]
- Catkin stack issues finally resolved/worked around.
- Turtlebot create 2.0 released.
- Final kobuki description and desktop (-gazebo) stacks released.

**Comment by stonier** [comment]
- turtlebot, turtlebot_apps, turtlebot_viz 2.0.0 releases

**Comment by stonier** [comment]
- kobuki 0.3.5 udev rule bugfix release.

**Comment by corot** [comment]
- turtlebot_apps 2.0.1 releases

**Comment by corot** [comment]
Releases related with robot visualization:
- kobuki_description 0.3.2 released
- turtlebot 2.0.1 released
- turtlebot_viz 2.0.1 released
- turtlebot_create 2.0.1 released

**Comment by stonier** [comment]
- yujin_ocs 0.2.3 released : catkin metapackage updates.

**Comment by stonier** [comment]
- kobuki 0.3.7 : minor bugfixes to the driver.

**Comment by stonier** [comment]
- kobuki_desktop 0.1.6 : bugfix for kobuki_qtest_suite

**Comment by stonier** [comment]
- turtlebot_apps 2.0.2 : boot munching following squashed, create calibration working again.

**Comment by corot** [comment]
- kobuki 0.3.8 : shaky motions with navi stack  bugfix on the driver. Fix also issue #257.

**Comment by corot** [comment]
- kobuki 0.3.9: Fix (again) issue #257. Now in auto-docking package. Softbot released

**Comment by corot** [comment]
- kobuki 0.3.9-1: Fix on softbot dependencies

**Comment by corot** [comment]
- kobuki 0.3.9-1: Fix on softbot dependencies
- kobuki 0.3.9-2: Softbot dropped by now, as it's getting a pain in there

**Comment by corot** [comment]
Starting Hydro releases!
- yujin_ocs 0.3.0

**Comment by corot** [comment]
With Hydro we'll keep track of release only here: https://github.com/yujinrobot-release/yujin_release/wiki/_preview
