### ISSUE TITLE
Move Create/Kobuki params into own each specific package

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#34]
Those parameters are Create/Kobuki-specific and are not directly related with Turtlebot. So:

turtlebot / turtlebot_bringup / param / create -> turtlebot_create / param
turtlebot / turtlebot_bringup / param / kobuki -> kobuki/param

**Comment by bit-pirate** [comment]
- base params for kobuki have been moved (create does not have them)
- moving diagnostics still needs to be done (linked to moving create stack)

**Comment by stonier** [comment]
Decided to keep things centralised as much as possible - easier for devs to see what's going on with turtlebot launch and configuration.

This is really true when we get to apps, often there won't be an equivalent kobuki/create package, so they need to be next to the app launcher.

**Comment by bit-pirate** [comment]
Still fighting for keeping things separate! :-)

**Comment by stonier** [comment]
Ok, persuaded. Moving management of constant params to their respective packages like openni.launch does (not that it does that well). Can't do so easily with diagnostics, since it's a mix of parameters.

**Comment by bit-pirate** [comment]
Nice! :-)
