### ISSUE TITLE
minimal.launch with ROS_HOSTNAME set not working

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#39]
If ROS_HOSTNAME is set,  minimal.launch does not work.

I think it is the same issue that Marcus and Daniel found... roscpp issue..

**Comment by ahendrix** [comment]
This is probably related to https://github.com/ros/ros_comm/issues/35

**Comment by stonier** [comment]
Fixed, look for ros_comm v1.9.37 to come out.
