### ISSUE TITLE
Move view_xxx.launch to desktop

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#4]
Currently lurking in turtlebot_bringup, but should be in one of the desktop packages instead.

**Comment by stonier** [comment]
Convert the [turtlebot_viz](http://ros.org/wiki/turtlebot_viz) stack and bring it to github, create a package for these here.

**Comment by stonier** [comment]
Move the diagnostics launcher there too?

**Comment by LucidOne** [comment]
As far as I understand we need a package called turtlebot2_description
or kobuki_description in addition to a package called 
turtlebot_description. The turtlebot 1 urdf should still be accessible
for backwards compatibility.

**Comment by stonier** [comment]
Descriptions are different - I'm just looking at moving various tools and utilities that are for monitoring purposes out of 'bringup'. I'm currently abusing the idea of bringup by putting them there now.

**Comment by stonier** [comment]
Moved the model viewer to turtlebot_description in fe5657c8c4813bb93949b8949e92a3bd9724c66f.

**Comment by stonier** [comment]
Moved them all to turtlebot_viz/turtlebot_rviz_launchers.
