### ISSUE TITLE
REP Modifications

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#40]
- '''base size''' : kobuki is 35cm, rep states 33cm
- '''base_link''' : less ambiguous is base_footprint as a reference

Previous comments from Marcus about the base_link.

> Can we change the REP to define a fixed transform from 
> base_footprint -> camera_rgb_frame instead using the 
> more arbitrary base_link?
> 
> Since we usually put base_link on the axis of the main 
> wheels for our (centred) differential drives, I added a 
> base_bottom_link at the bottom surface of the Kobuki. 
> Now, base_bottom_link 0> camera_rgb_frame aligns with REP115.
> 
> If we adjust the REP this will be obsolete

**Comment by mmwise** [comment]
Hi Daniel -

The reason we use base_link is because REP 105 calls out base_link as the
definitive base link for mobile platforms, some of the ROS software has
been changed to only use the base link and not base_footprint.

Also are you sure you meant REP115? do you mean REP119?

On Fri, Dec 14, 2012 at 11:41 PM, Daniel Stonier
notifications@github.comwrote:

> - '''base size''' : kobuki is 35cm, rep states 33cm
> - '''base_link''' : less ambiguous is base_footprint as a reference
> 
> Previous comments from Marcus about the base_link.
> 
> Can we change the REP to define a fixed transform from
> base_footprint -> camera_rgb_frame instead using the
> more arbitrary base_link?
> 
> Since we usually put base_link on the axis of the main
> wheels for our (centred) differential drives, I added a
> base_bottom_link at the bottom surface of the Kobuki.
> Now, base_bottom_link 0> camera_rgb_frame aligns with REP115.
> 
> If we adjust the REP this will be obsolete
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/40.

## 

Manager of Robot Development
Willow Garage
68 Willow Rd.
Menlo Park, Ca 94025

**Comment by tfoote** [comment]
base_link and base_footprint are not interchangeable.  base_link is attached to the body.  base_footprint is flattened onto the ground.  In the TurtleBot we simply set it as a fixed offset, which means that it does not correct for tipping.  In the Kobuki it would be better to take advantage of the gyro and correct for the roll and pitch like is done on the PR2.  (This will help a lot for uneven ground etc) 

In the long run we should be converging on [REP 105](http://ros.org/reps/rep-0105.html) Where odom->base_link is just a single step.  There is a ticket to be opened against robot_pose_ekf ros-planning/navigation#15 to take into account the gyro inputs and do this properly.  

Extending the base size to 35cm would be a good fix to support the TurtleBot2.

**Comment by stonier** [comment]
Ok, I'm fine with keeping to a convention (REP 105). 

We may need a rethink if someone puts on a considerably different base in future though (e.g. much bigger wheels and base clearance). It'll either force that base_link into open air to meet the requirement, or significantly shift the kinect view where it matters - i.e. closest field of view intersection with the ground.

May not ever be an issue so Marcus, let's only cross that hurdle if we get there and aim to keep things consistent with convention for now.
