### ISSUE TITLE
Flying Asus

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#42]
It doesn't include a mesh for a mount yet, so when you view the robot model (see turtlebot/turtlebot_descriptions/readme.txt), it looks like it's flying.

**Comment by bit-pirate** [comment]
We will need to agree on a mount first, then we can add the mount's mesh to the URDF descriptions.

**Comment by jihoonl** [comment]
The new mesh for default asus setup has mount. This should be no problem as of now.

**Comment by jihoonl** [comment]
![turtlebot](https://cloud.githubusercontent.com/assets/1556736/6321785/f57fb0f4-bb48-11e4-8a43-fd626679cae5.png)
