### ISSUE TITLE
Openni crashing

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#5]
The nodelet from openni_camera seems to be crashing alot

```
nodelet: /usr/include/boost/smart_ptr/shared_ptr.hpp:412: boost::shared_ptr<T>::reference boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo, boost::shared_ptr<T>::reference = xn::NodeInfo&]: Assertion `px != 0' failed.
[FATAL] [1348746869.679027201]: Service call failed!
[FATAL] [1348746869.679040401]: Service call failed!
[FATAL] [1348746869.679055188]: Service call failed!
[FATAL] [1348746869.679072983]: Service call failed!
[openni_manager-1] process has died [pid 2559, exit code -6, cmd /opt/ros/fuerte/stacks/nodelet_core/nodelet/bin/nodelet manager __name:=openni_manager __log:=/home/snorri/.ros/log/744d67de-0898-11e2-9325-6cf049781259/openni_manager-1.log].
log file: /home/snorri/.ros/log/744d67de-0898-11e2-9325-6cf049781259/openni_manager-1*.log
respawning...
```

Try the heavier openni_launch?

**Comment by stonier** [comment]
New openni packages:
- http://userpages.uni-koblenz.de/~lsarnecki/deb/

Also...that nodelet may be a bit crashy. Test openni_launch and see if its not so crash, even if its a bit heavier.

**Comment by stonier** [comment]
Nodelet is still definitely very crashy.

**Comment by stonier** [comment]
The openni_launch is crashing the same way...about 50% of the time.

**Comment by tfoote** [comment]
There's several versions of openni we're trying to figure out which one is most stable.  Unfortunately the newest one is not necessarily more stable. @vrabaud have we made progress on choosing this?

**Comment by vrabaud** [comment]
That is the typical error where you need to do a "killall -9 XnSensorServer". The latest version of OpenNI in unstable (1.5.4) is the best but it can still lead to errors. I think we all agreed to release it for Oneiric/Precise. Let me push Jon for that.

**Comment by stonier** [comment]
Now we're concentrating on groovy...refer to #32 for a continuation of the issues around 3d sensors.
