### ISSUE TITLE
ROS wiki checklist

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#52]
Kobuki/Turtlebot wiki pages that are missing or must be updated. Fill free to include any issues you find in the "todo" list.

Make sure these have fuerte/groovy versioning tags where appropriate.
- <del>[Kobuki Params](https://github.com/yujinrobot/kobuki/issues/221)</del>
- <del>[wiki/Robots/Turtlebot](http://ros.org/wiki/Robots/TurtleBot)</del>
- <del>[wiki/turtlebot/Tutorials](http://www.ros.org/wiki/turtlebot/Tutorials) - need a better framework for pre_groovy/post-groovy</del>
- <del>[3d Sensor Tutorial](http://www.ros.org/wiki/turtlebot/Tutorials/Looking at Camera Data)</del> - update pics and explanation about depth image vs point clouds.
- <del>[Deb Installation](http://ros.org/wiki/turtlebot/Tutorials/groovy/Debs%20Installation)</del> - installation from debs.
- <del>[Source Installation](http://ros.org/wiki/turtlebot/Tutorials/groovy/Source%20Installation)</del> - split catkin/non-catkin installation instructions from source.
- <del>[Contributing Section](http://ros.org/wiki/Robots/TurtleBot/groovy/Contributing)</del>
- [Panorama Tutorial](http://ros.org/wiki/turtlebot_panorama) - flesh this one out, with panorama app
- <del>[Turtlebot Dashboard](http://ros.org/wiki/turtlebot_dashboard)</del> - woefully out of date, needs new pics and explanation.
- [TurtleBot Bringup](http://ros.org/wiki/turtlebot_bringup/Tutorials) - needs updates for 'usb installed' sections
- [Usb Installations](http://www.ros.org/wiki/turtlebot/Tutorials) - needs updates for 'usb installed' sections (install, post install, workstation and network tutorials)
- [Android App Section](http://ros.org/wiki/Robots/TurtleBot) - pending the android app overhaul
- [Simulation Tutorials](http://www.ros.org/wiki/turtlebot/Tutorials) - pending gazebo simulations up and running

**Comment by jihoonl** [comment]
We should state Kinect only works with USB 2.0 somewhere!!

**Comment by stonier** [comment]
Added to the 3d visualisation tutorial.

**Comment by stonier** [comment]
Fleshed out complete instructions for the split catkin, non-catkin source installs.

**Comment by stonier** [comment]
Everything done except for simulation (hydro) and iso instructions (bill)
