### ISSUE TITLE
Break out linux_hardware

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#54]
Causing us issues for dashboards. Currently kobuki_desktop and turtlebot_create_desktop depend on turtlebot. 

Turtlebot should be on top!

Still, we need a better way of loading up the dashboards for different hardware. Consider on the way to hydro.

**Comment by mikeferguson** [comment]
This should probably become it's own standalone package/repo over in ros-drivers -- it's pretty generic.

We might want to consider calling it something like "laptop_tools" or "laptop_utils" as it really is based on laptop hardware, not so much on linux.

**Comment by stonier** [comment]
Sounds like the right place. Auto-detecting cross platform support could very easily be built into the one program I think (if it ever needs it).

I'll break it out later after 2.0 release. 

For now, I just wondered why dashboard is using topics for the laptop battery. It uses the diagnostics for everything else. So if we go back to diagnostics for the laptop battery, this temporary ugly stack dependency problem will go away.

**Comment by jihoonl** [comment]
The reason we named it as linux_hardware was to support of sbc board like embedded systems later. That is why we made the name very generic.

**Comment by stonier** [comment]
Put in diagnostics parsing instead of using the subscriber directly (ironically, like it does for everything else). I think its wierd that you convert from binary to strings in diagnostics and then back to binary form here though. Only upside is that diagnostics is a slow frequency burner compared to most binary msg topics. Anyway, it removes the ugly turtlebot dependency for now.

https://github.com/yujinrobot/kobuki_desktop/commit/dc219966fe46243118162e5a55934bc15ce27ee0
https://github.com/turtlebot/turtlebot_create_desktop/commit/8f247505093f387f33c8e280ead4ce1f0929137c

This also adds the charging state to the laptop battery display.

**Comment by stonier** [comment]
Leaving this as todo though to break it out like mike suggested when catkinizing.

**Comment by corot** [comment]
We are releasing turtlebot hydro with linux_hardware package included....

just a reminder

**Comment by jihoonl** [comment]
Is it still valid issue?

**Comment by jihoonl** [comment]
It has been moved to ros-drivers repository.

https://github.com/ros-drivers/linux_peripheral_interfaces/issues/1
