### ISSUE TITLE
turtlebot is not building on groovy

### ISSUE THREAD

**Issue by tfoote** [turtlebot/turtlebot#56]
http://jenkins.willowgarage.com:8080/view/GbinO64/job/ros-groovy-turtlebot_binarydeb_oneiric_amd64/

This error usually is a missing stack level dependency. 

```
 [rospack] Error: package/stack 'turtlebot_bringup' depends on non-existent package 'kobuki_description' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'


  CMake Error at /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:129 (message):


    Failed to invoke rospack to get compile flags for package
    'turtlebot_bringup'.  Look above for errors from rospack itself.  Aborting.
    Please fix the broken dependency!

  Call Stack (most recent call first):
    /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:203 (rosbuild_invoke_rospack)
    CMakeLists.txt:12 (rosbuild_init)
```

**Comment by tfoote** [comment]
@dirk-thomas fyi filed here

**Comment by stonier** [comment]
I'm on it.

Catkinizing kobuki was the last step before a 2.0 release. That rewiring is causing some issues down the line.

fyi: kobuki_description should be there now, it was just awaiting a first build on jenkins.

There is another issue to fix now though - dependencies moving from stacks to packages muck things up.

**Comment by stonier** [comment]
2.0.0 precise stacks are building...quantal I got caught out with an old rosrelease again, but on their way now.
