### ISSUE TITLE
Robot Descriptions and Models

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#6]
Some thoughts:
- Keep using turtlebot_descriptions, no real need for a new package.
- Also keep kobuki_descriptions, some people will may wish to build non-turtlebot kobuki platforms.
- Move the new stacks and poles descriptions into turtlebot_description.
- Use the new ones by default, provide an argument for loading up the old ones.
- Roslaunch 'base' argument and TURTLEBOT_BASE environment variable (create, khobuki).
- Roslaunch  'stacks' argument and TURTLEBOT_STACKS environment variable (circles, hexagons).
- Roslaunch  '3d_sensor' argument and TURTLEBOT_3D_SENSOR environment variable (kinect, asus_xtion_live_pro).

Probably need to take care working out how to bring in the appropriate pieces for urdf's and such.

**Comment by stonier** [comment]
Changes in robot descriptions:

**Camera link transform** :    previously relative to plate 2. However plates aren't fixed in the [REP](http://www.ros.org/reps/rep-0119.html) and ours differ also. REP does specify a transform relative to the base link, which we've followed, so we'll set up the kinect xacro's camera link relative to the base link at that distance.

**Comment by stonier** [comment]
9d44ccfb77324de3bb0286de4d75361705af0bd0 starts moving to the component based xacros and reconfigures the kinect in particular to work off the REP specified base_link to rgb camera parameters.

**Comment by stonier** [comment]
f4c3dc644bc041a4cfe772a6970a888b0857ecc1 and e97f5844a53caf58c67c35313817c13826c66c9d provide a launcher for publishing and viewing the various robot models (defined by args).

**Comment by stonier** [comment]
880f41fdd784172e269174d17be620062057ca1a is pretty messy, but does a few things:
- consolidates component xacros around properties defined for the REP base_link-camera_rgb_frame specification. 
- Gets the asus xtion pro (with mesh) to show up properly in rviz.
- Sets measured defaults for prime sense rgb-depth frame transform (#9). 

We'll do a proper calibration test later to verify transforms for the kinect/xtion pro later (mostly for our curiosity).

**Comment by bit-pirate** [comment]
We just stumbled upon another detail:

The REP specifies the exact _base_link_ -> _camera_rgb_frame_ transformation. I am used to put _base_link_ on the axis of the main wheels and in the middle between both. However, for the Turtlebot and REP it looks like _base_link_ is located at the bottom of the iCreate body.

I recommend moving the _base_link_ up to the axis of the main wheels and adjust the REP and iCreate URDF to reflect this change.

In detail, the new iCreate _base_link_ would be ca. 0.035m (Does somebody have an exact measurement of the main wheel diameter?) above _base_footprint_ (before 0.017m) and the z-offset in the REP transform would change from 0.287m to 0.269m.

Any remarks/objections?

**Comment by stonier** [comment]
I'd like that - but just copied the create method for now (base_link refers to the point on the bottom of the base mould) as it was less work. I think we should be using base_footprint in the long run anyway. 

Refer to 70bc4f907aeb6e921bce303c675d176b5b737086.

**Comment by bit-pirate** [comment]
_bump_
Can we change the REP to define a fixed transform from base_footprint -> camera_rgb_frame instead using the more arbitrary base_link?

Since we usually put base_link on the axis of the main wheels for our (centred) differential drives, I added a base_bottom_link at the bottom surface of the Kobuki. Now, base_bottom_link 0> camera_rgb_frame aligns with REP115.
If we adjust the REP this will be obsolete.

**Comment by stonier** [comment]
REP discussion continuing in #40
