### ISSUE TITLE
hydro-devel turtlebot_bringup requires rocon_hub.

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#64]
If rocon_hub is not running, it crashes.

@stonier

**Comment by stonier** [comment]
How, why?

I wonder if this is the problem Sarah is having as well.

**Comment by stonier** [comment]
Probably fixed by this one: https://github.com/robotics-in-concert/rocon_app_platform/commit/b507a2bcf9e809e4d87e2cf400c2c73c63892681

Reopen if necessary.
