### ISSUE TITLE
turtlebot 1 visualisation broken

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#65]
;-(

**Comment by jihoonl** [comment]
unit aware issue?

**Comment by jihoonl** [comment]
@bit-pirate  https://github.com/ros-visualization/rviz/issues/622

**Comment by bit-pirate** [comment]
https://github.com/turtlebot/turtlebot/pull/66
https://github.com/turtlebot/turtlebot_create/pull/7

**Comment by bit-pirate** [comment]
turtlebot_create version 2.0.1 fixes this issue. It's now available on shadow-fixed.
