### ISSUE TITLE
Fix app manager closure

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#8]
It bugs out when ctrl-c'ing.

Not a priority, maybe really not a priority if we want to replace it shortly anyway.

**Comment by jihoonl** [comment]
Ticket is issued in kforge app mandroid project in kforge. Will wait for a week and decide whether we migrate the app_manager code into turtlebot organization

**Comment by stonier** [comment]
I'm going to bring in a patched version into turtlebot. We want to replace this in the near future anyway after redesigning with brian (osrf), here (turtlebot sig) and austin.

**Comment by stonier** [comment]
The ticket was here: https://kforge.ros.org/appmanandroid/trac/ticket/29
