### ISSUE TITLE
migrate turtlebot rapp list file from bringup to coreapp pkg.

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#81]
Since turtlebot_bringup does not depend on core apps, keeping rapp list file in the core app makes more sense. otherwise, it causes error.

**Comment by stonier** [comment]
Marcus has a good point - if you put the rapp list in turtlebot_bringup ,then you are listing apps which have no guarantee whether they are installed or not. That is not ideal.

**Comment by stonier** [comment]
Better solution is to get the rapp manager to quietly ignore the turtlebot_apps rapp list if it can't be actually found on the filesystem. It will still load the rocon_apps rapp list.

Issue continuing over on rocon.

https://github.com/robotics-in-concert/rocon_app_platform/issues/62
