### ISSUE TITLE
turtlebot_bringup: rocon dependencies missing

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#85]
Using `rocon_launch turtlebot_bringup concert.launch` requires a couple of ROCON dependencies, which are not pulled during install. The dependencies are:
- rocon_hub
- rocon_gateway

**Comment by stonier** [comment]
rocon_launch doesn't need it, but concert.launch does. I see no problem adding rocon_hub and rocon_gateway to the dependencies for turtlebot_bringup, but these should automatically be brought in if the rocon_app_manager is a dependency?

**Comment by bit-pirate** [comment]
Ahm, I made a small mistake. The concert launcher is actually `turtlebot_bringup/bringup.concert`.
It contains `paired_public.launch` and `minimal_with_appmanager.launch`. Looking into both I can find only one dependency not being part of turtlebot and that is the `rocon_app_manager`. However, this package is already listed in the `package.xml`.

Strangely, both `rocon_hub` and `rocon_gateway` are also already listed as dependencies of the `rocon_app_manager`.

Maybe it was just some strange mix-up on my system. I have just re-released turtlebot. So I will test this again once the debs are out.

**Comment by stonier** [comment]
Ok, should be fine then - reopen if necessary.
