### ISSUE TITLE
Kinect Transform is Jumping

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#9]
It's bouncing around in rviz when using openni.launch.

**Comment by stonier** [comment]
Our openni is publishing a transform...that doesn't match our xacro file. Currently, we've turned tf publishing in openni but if we we want to use the openni launcher probably should disable the transform in the xacro file and let openni do it's job. Does the same apply to the openni_camera nodelet?

```
  <include file="$(find openni_launch)/launch/openni.launch" ns="/">
    <arg name="camera" value="$(arg camera)"/>
    <arg name="publish_tf" default="false"/>
```

**Comment by tfoote** [comment]
I would suggest keeping it off in the camera and defined in the xacro.  That keeps all the tree info coming from one place.  The openni publishing tf is mostly so that a camera unattached to anything can be viewed in rviz.

**Comment by stonier** [comment]
Ok, that logic makes good sense...just have to work out why it's publishing a slightly offset frame then.

**Comment by stonier** [comment]
After some recent hacking to get the robot xacro files updated for kobuki, this came back to bite. I believe they took out the kinect_frames launcher to get it to work. But it worries me that we don't know why it was working for the create based turtlebot originally.

We need to get to the bottom of it this week.

**Comment by stonier** [comment]
Ok, I finally sat down myself and had a good look at this. I'm seeing no less than three different definitions for the camera_link->camera_depth_frame and camera_link->camera_link->camera_rgb_frame transforms. Values below are for the y components of the transforms in each of the two transforms
- kinect_frames.launch : -0.025 and -0.045
- current turtlebot xacro : 0.018 and -0.005
- the yujin lads xacro : 0.0125 and -0.0125

Wow, significantly different. Why? Assuming the camera_link is centred in the middle of the kinect (where that mounting piece is), then our kinect hardware here rather does seem to match what the yujin lads measured a while ago.
- Are there multiple kinect models out there (I don't think so)?
- The kinect frames shows the official openni launch values, which are used by default, so I'm guessing _alot_ of folk are using these. To our kinect though, they look horribly wrong (both to one side of the camera_link, when it appears quite obvious that they are located either side of camera_link).

If anyone has any input on why there are such significant differences here, I'm all ears.

Note: you can find images showing Young Hoon's investigation into the hardware below:
- [Kinect Hardware](http://files.yujinrobot.com/kobuki/kinect_frames/turtlebot_hw.png)
- [Kinect Transforms](http://files.yujinrobot.com/kobuki/kinect_frames/turtlebot_urdf.png) : using current turtlebot xacro settings.

**Comment by stonier** [comment]
- Set measured defaults in the kinect/xtion xacros for the rgb-depth frame transform in 880f41fdd784172e269174d17be620062057ca1a.
- Removed kinect_frames includes everwhere in turtlebot/turtlebot_apps/issues/12.

We'll do a proper calibration test later to verify transforms for the kinect/xtion pro later (mostly for our curiosity).

**Comment by stonier** [comment]
Closing for now - it's working for us, reopen if necessary later or we missed something.
