### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#91]
- [x] turtlebot
- [x] turtlebot_msgs
- [x] turtlebot_apps
- [x] turtlebot_create
- [x] turtlebot_create_desktop
- [x] turtlebot_viz
- [x] turtlebot_simulator
- [x] kobuki
- [x] kobuki_desktop
- [x] kobuki_msgs
- [x] yujin_ocs

**Comment by stonier** [comment]
@bit-pirate reckons catkin_xxx command does something with changelogs.

**Comment by stonier** [comment]
@bit-pirate likes @bit_pirate_xxx

**Comment by tfoote** [comment]
catkin_generate_changelog and catkin_tag_changelog are the magic xxx for
@bit-pirate

http://www.ros.org/wiki/bloom/Tutorials/ReleaseCatkinPackage

**Comment by stonier** [comment]
Oooh, thanks for the pointer tully.
