### ISSUE TITLE
What _mobile_base_soft.launch does on turtlebot_bringup?

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#92]
I think we must remove it

**Comment by bit-pirate** [comment]
@jihoonl smuggled this one in (https://github.com/turtlebot/turtlebot/commit/60aafbe049c8b38773e80eb5c231ef4f5254dd84). Agreeing in removing it. Please checked, if anything is using it.

**Comment by corot** [comment]
die, die, die
