### ISSUE TITLE
Update upstart files

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#94]
Just stumbled over this upstart folder., which looks outdated to me, e.g. from `turtlebot.launch` : 

```
  <!-- sample file, copy this to /etc/ros/electric/turtlebot.launch -->
```

Someone knows what needs to be done with this?

**Comment by bit-pirate** [comment]
@stonier @corot @yhju maybe?

**Comment by stonier** [comment]
Its the old bootup script so turtlebot autostarts. Useful to have for people who install debs. Saves them having to figure it out for themselves but we never got around to supporting it. Id delete it for now and reintegrate if we ever do it ourselves.

**Comment by bit-pirate** [comment]
+1 for removing it. It is still in the history and we avoid confusing people, e.g. that turtlebot.launch turns up in the tab completion for turtlebot_bringup.

Any objections?

**Comment by bit-pirate** [comment]
If we need anything from this directory for Hydro, just reintroduced it.

**Comment by LucidOne** [comment]
I'm updating https://github.com/TurtleBot-Mfg/ros-system-daemon-groovy for Hydro now.

+1 Remove from turtlebot_bringup
