### ISSUE TITLE
Frequent openni failure on precise

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#98]
Quite often getting:

```
terminate called after throwing an instance of 'openni_wrapper::OpenNIException'
  what():  unsigned int openni_wrapper::OpenNIDriver::updateDeviceList() @ /tmp/buildd/ros-hydro-openni-camera-1.9.0-0precise-20130820-0515/src/openni_driver.cpp @ 125 : enumerating image nodes failed. Reason: One or more of the following nodes could not be enumerated:

Image: PrimeSense/SensorV2/5.1.0.41: Got a timeout while waiting for a network command to complete!
```

and then lots of bleeding from the image nodelets. After failure:

```
$ ps aux |grep Xn
snorri    7509  0.0  0.0  13128   928 pts/5    S+   19:45   0:00 grep --color=auto Xn
snorri   29783  0.0  0.0 406656  4456 ?        Ssl  19:40   0:00 /usr/lib/libopenni-sensor-primesense0/XnSensorServer /etc/openni
snorri@snorriwork64:/mnt/ros/turtlebot/src/turtlebot_apps/turtlebot_core_apps$ kill -s 9 29783
snorri@snorriwork64:/mnt/ros/turtlebot/src/turtlebot_apps/turtlebot_core_apps$ ps aux |grep Xn
snorri    7525  0.0  0.0  13128   932 pts/5    S+   19:46   0:00 grep --color=auto Xn
```

fixes the problem. Not a very good situation.

**Comment by bit-pirate** [comment]
That (XnSensor not shutting down) is a known problem. [OpenNi2](https://github.com/ros-drivers/openni2_launch) might be a solution.

**Comment by mikeferguson** [comment]
@stonier, you might look into openni2_camera moving forward. It's many times more robust than openni_camera. Once the packages.ros.org stuff is all moved over to OSU, the debs I released last week will be in shadow fixed.

**Comment by bit-pirate** [comment]
:smile:

**Comment by mikeferguson** [comment]
@bit-pirate -- I will probably get debs released of openni2_launch before the end of this week -- first I want to gut it and make a thin wrapper around rgbd_launch (as was already done for openni_launch and freenect launch)

**Comment by stonier** [comment]
Great, thanks for the heads up.

**Comment by bit-pirate** [comment]
Do we want to get this in before or after we release officially for Hydro?

I prefer to do it after.

**Comment by mikeferguson** [comment]
btw -- I thought about it afterwards -- and openni2 isn't going to help turtlebot, since most of them use kinects -- the openni2_camera stuff is only for asus/primesense sensors, and I believe the recommended driver for kinects is now freenect + rgbd_launch 

@piyushk can you confirm that freenect is what is generally being recommended, that was what I understood from discussions a few weeks back?

**Comment by mikeferguson** [comment]
I should also note, that with rgbd_launch being used as the basis for launch files for both freenect and openni2_camera, it should be pretty seamless going between the two with all the same topic names/etc.

**Comment by bit-pirate** [comment]
I thought OpenNI2 will be more stable in general. OpenNI camera uses the
OpenNI libray version 1.5.4 (I think), which is quite outdated.

2013/9/10 Michael Ferguson notifications@github.com

> I should also note, that with rgbd_launch being used as the basis for
> launch files for both freenect and openni2_camera, it should be pretty
> seamless going between the two with all the same topic names/etc.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/98#issuecomment-24150549
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by mikeferguson** [comment]
openni2 will be more stable -- but the libopenni2 package that is released into PCL (and ROS, as that is what we are pulling) does not include the numerous kinect-specific hacks that were added to the old libopenni to support kinects. My understanding from talking to upstream maintainers was that the preference was to use freenect (which has become very stable) for kinects, and use openni2 only for official primesense/asus sensors (including the newer versions such as carmine).

I haven't used a Kinect in ages, as I use primarily new 1.082 and 1.09 Primesense sensors and the occasional asus xtion pro live, so I sorta forgot the other day that 99% of Turtlebots use the Kinect.

**Comment by piyushk** [comment]
@mikeferguson I'm afraid I have no idea if freenect is recommended over openni2.

@stonier I can confirm your original bug report. I also know that it cropped up the instant I installed ros-hydro-pcl-conversions (i.e. libpcl-1.7-all-dev). I thought it was an issue specific to my machine, so I was planning on testing on other machines I had not updated yet. It should be a pretty easy test - I will get back to you soon.

As a side note, I don't use openni anymore. As @mikeferguson said, with the recent migration of openni_launch, freenect_launch and openni2_launch to all use rgbd_launch - the migration from one to the other is trivial. See if freenect_launch solves your problem.

**Comment by piyushk** [comment]
@stonier I take it back. I cannot reproduce the problem anymore.

I have one guess though. On the day Hydro released, there was a dependency conflict between hydro-pcl-conversions and hydro-openni-camera (PCL was pulling in an outdated version of openni). The issue has since been fixed. Can you verify the following:
- openni-dev and ps-engine are NOT installed
- libopenni-dev is installed at 1.5.4.0-4+precise1
- libopenni-sensor-primesense-dev is installed at 5.1.0.41-2+precise1

**Comment by stonier** [comment]
Closing this - we have it working fine on precise and trusty now and have had no news for a while. Open a new ticket if there are fresh problems.
